global:
  smtp_smarthost: 'mailhog:1025'
  smtp_from: 'alerts@sast-platform.local'
  smtp_auth_username: ''
  smtp_auth_password: ''
  smtp_require_tls: false

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'web.hook'
  routes:
    # Critical security alerts
    - match:
        severity: critical
      receiver: 'critical-alerts'
      group_wait: 0s
      repeat_interval: 5m
    
    # High severity alerts
    - match:
        severity: warning
      receiver: 'warning-alerts'
      repeat_interval: 15m
    
    # SAST-specific alerts
    - match:
        alertname: CriticalVulnerabilitiesFound
      receiver: 'security-team'
      group_wait: 0s
      repeat_interval: 5m

receivers:
  # Default webhook receiver
  - name: 'web.hook'
    webhook_configs:
      - url: 'http://sast-runner:8080/alerts'
        send_resolved: true

  # Critical alerts - immediate notification
  - name: 'critical-alerts'
    email_configs:
      - to: 'security-team@company.local'
        subject: '🚨 CRITICAL: {{ .GroupLabels.alertname }} - {{ .GroupLabels.repository }}'
        body: |
          🚨 **CRITICAL SECURITY ALERT** 🚨
          
          **Alert:** {{ .GroupLabels.alertname }}
          **Repository:** {{ .GroupLabels.repository }}
          **Severity:** {{ .GroupLabels.severity }}
          **Time:** {{ .FiringAlerts | len }} alerts firing
          
          **Details:**
          {{ range .Alerts }}
          - **Description:** {{ .Annotations.description }}
          - **Summary:** {{ .Annotations.summary }}
          - **Started:** {{ .StartsAt }}
          {{ end }}
          
          **Actions Required:**
          1. Investigate immediately
          2. Review scan results in Grafana
          3. Block deployment if necessary
          
          **Dashboard:** http://localhost:3001/d/sast-security-dashboard
          **Logs:** http://localhost:3001/explore (Loki)
    
    slack_configs:
      - api_url: '${SLACK_WEBHOOK_URL}'
        channel: '#security-critical'
        color: 'danger'
        title: '🚨 Critical Security Alert'
        text: |
          Critical vulnerabilities detected in {{ .GroupLabels.repository }}
          
          {{ range .Alerts }}
          • {{ .Annotations.summary }}
          {{ end }}
          
          <http://localhost:3001/d/sast-security-dashboard|View Dashboard>

  # Warning alerts
  - name: 'warning-alerts'
    email_configs:
      - to: 'devops-team@company.local'
        subject: '⚠️ SAST Warning: {{ .GroupLabels.alertname }}'
        body: |
          ⚠️ **SAST Warning Alert**
          
          **Alert:** {{ .GroupLabels.alertname }}
          **Repository:** {{ .GroupLabels.repository }}
          **Severity:** {{ .GroupLabels.severity }}
          
          {{ range .Alerts }}
          **Summary:** {{ .Annotations.summary }}
          **Description:** {{ .Annotations.description }}
          {{ end }}
          
          **Dashboard:** http://localhost:3001/d/sast-security-dashboard

  # Security team specific alerts
  - name: 'security-team'
    email_configs:
      - to: 'security-team@company.local'
        subject: '🔒 Security Alert: {{ .GroupLabels.alertname }}'
        body: |
          🔒 **Security Team Alert**
          
          **Alert:** {{ .GroupLabels.alertname }}
          **Repository:** {{ .GroupLabels.repository }}
          **Time:** {{ .FiringAlerts | len }} alerts firing
          
          **Critical Vulnerabilities:**
          {{ range .Alerts }}
          {{ if eq .Labels.severity "critical" }}
          - {{ .Annotations.summary }}
          {{ end }}
          {{ end }}
          
          **High Vulnerabilities:**
          {{ range .Alerts }}
          {{ if eq .Labels.severity "high" }}
          - {{ .Annotations.summary }}
          {{ end }}
          {{ end }}
          
          **Recommended Actions:**
          1. Review vulnerability details in Grafana
          2. Check scanner logs in Loki
          3. Coordinate with development team
          4. Update security policies if needed
          
          **Links:**
          - Dashboard: http://localhost:3001/d/sast-security-dashboard
          - Logs: http://localhost:3001/explore
          - Metrics: http://localhost:9090

    webhook_configs:
      - url: 'http://sast-runner:8080/security-webhook'
        send_resolved: true
        http_config:
          bearer_token: '${SECURITY_WEBHOOK_TOKEN}'

# Inhibition rules
inhibit_rules:
  # Inhibit warning if critical is firing
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'repository']

# Templates for custom formatting
templates:
  - '/etc/alertmanager/templates/*.tmpl'
