groups:
  - name: sast_security_alerts
    rules:
      # Alert for critical vulnerabilities
      - alert: CriticalVulnerabilitiesFound
        expr: sast_vulnerabilities_total{severity="critical"} > 0
        for: 0m
        labels:
          severity: critical
          team: security
        annotations:
          summary: "Critical vulnerabilities found in {{ $labels.repository }}"
          description: "Found {{ $value }} critical vulnerabilities in repository {{ $labels.repository }}"

      # Alert for high-priority vulnerabilities threshold exceeded
      - alert: HighVulnerabilitiesThresholdExceeded
        expr: sast_vulnerabilities_total{severity="high"} > 5
        for: 5m
        labels:
          severity: warning
          team: security
        annotations:
          summary: "High-priority vulnerabilities threshold exceeded"
          description: "Found {{ $value }} high-priority vulnerabilities in {{ $labels.repository }} (threshold: 5)"

      # Alert for failed SAST scans
      - alert: SASTScanFailed
        expr: sast_scan_status == 0
        for: 1m
        labels:
          severity: warning
          team: devops
        annotations:
          summary: "SAST security scan failed"
          description: "Security scan for {{ $labels.repository }} completed with errors"

      # Alert for slow SAST scans
      - alert: SASTScanTooSlow
        expr: sast_scan_duration_seconds > 1800  # 30 minutes
        for: 0m
        labels:
          severity: info
          team: devops
        annotations:
          summary: "SAST scan running too long"
          description: "Scan for {{ $labels.repository }} has been running for {{ $value }} seconds"

      # Alert for increasing vulnerability trend
      - alert: VulnerabilityTrendIncreasing
        expr: increase(sast_vulnerabilities_total[24h]) > 10
        for: 10m
        labels:
          severity: warning
          team: security
        annotations:
          summary: "Increasing vulnerability trend detected"
          description: "{{ $value }} new vulnerabilities found in {{ $labels.repository }} in the last 24 hours"
