# Bandit configuration file for Python security scanning
# Documentation: https://bandit.readthedocs.io/en/latest/config.html

# Tests to skip (by test ID)
skips:
  # Skip these test IDs if they produce too many false positives
  # - B101  # assert_used - Skip if using assert for testing
  # - B601  # paramiko_calls - Skip if using paramiko legitimately
  # - B602  # subprocess_popen_with_shell_equals_true - Skip if shell=True is needed

# Tests to include (by test ID) - if not specified, all tests are run
# tests:
#   - B101
#   - B102

# Exclude specific directories and files
exclude_dirs:
  - '/tests'
  - '/test'
  - '/venv'
  - '/env'
  - '/.venv'
  - '/node_modules'
  - '/vendor'
  - '/__pycache__'
  - '/.git'
  - '/build'
  - '/dist'
  - '/docs'
  - '/migrations'  # Django migrations often have SQL injection-like patterns

# Confidence level filter
confidence: 
  - HIGH
  - MEDIUM
  # - LOW  # Uncomment to include low confidence findings

# Severity level filter  
severity:
  - HIGH
  - MEDIUM
  # - LOW  # Uncomment to include low severity findings

# Specific rules configuration
bandit_config:
  # B101: assert_used
  assert_used:
    skips: ['*_test.py', '*test*.py', 'test_*.py']
  
  # B102: exec_used
  exec_used:
    severity: HIGH
  
  # B103: set_bad_file_permissions  
  set_bad_file_permissions:
    severity: HIGH
  
  # B104: hardcoded_bind_all_interfaces
  hardcoded_bind_all_interfaces:
    severity: MEDIUM
  
  # B105: hardcoded_password_string
  hardcoded_password_string:
    severity: HIGH
    # Word list for password detection
    word_list: 
      - password
      - pass
      - passwd
      - pwd
      - secret
      - token
      - key
      - api_key
      - auth
      - credential
  
  # B106: hardcoded_password_funcarg
  hardcoded_password_funcarg:
    severity: HIGH
  
  # B107: hardcoded_password_default
  hardcoded_password_default:
    severity: HIGH
  
  # B108: hardcoded_tmp_directory
  hardcoded_tmp_directory:
    severity: MEDIUM
    tmp_dirs: ['/tmp', '/var/tmp', '/dev/shm']
  
  # B110: try_except_pass
  try_except_pass:
    severity: LOW
  
  # B112: try_except_continue  
  try_except_continue:
    severity: LOW
  
  # B201: flask_debug_true
  flask_debug_true:
    severity: HIGH
  
  # B301: pickle
  pickle:
    severity: MEDIUM
  
  # B302: marshal
  marshal:
    severity: MEDIUM
  
  # B303: md5
  md5:
    severity: MEDIUM
  
  # B304: des  
  des:
    severity: HIGH
  
  # B305: cipher
  cipher:
    severity: HIGH
  
  # B306: mktemp_q
  mktemp_q:
    severity: MEDIUM
  
  # B307: eval
  eval:
    severity: HIGH
  
  # B308: mark_safe
  mark_safe:
    severity: MEDIUM
  
  # B309: httpsconnection
  httpsconnection:
    severity: MEDIUM
  
  # B310: urllib_urlopen
  urllib_urlopen:
    severity: MEDIUM
  
  # B311: random
  random:
    severity: LOW
  
  # B312: telnetlib
  telnetlib:
    severity: HIGH
  
  # B313: xml_bad_cElementTree
  xml_bad_cElementTree:
    severity: MEDIUM
  
  # B314: xml_bad_ElementTree
  xml_bad_ElementTree:
    severity: MEDIUM
  
  # B315: xml_bad_expatreader
  xml_bad_expatreader:
    severity: MEDIUM
  
  # B316: xml_bad_expatbuilder
  xml_bad_expatbuilder:
    severity: MEDIUM
  
  # B317: xml_bad_sax
  xml_bad_sax:
    severity: MEDIUM
  
  # B318: xml_bad_minidom
  xml_bad_minidom:
    severity: MEDIUM
  
  # B319: xml_bad_pulldom
  xml_bad_pulldom:
    severity: MEDIUM
  
  # B320: xml_bad_etree
  xml_bad_etree:
    severity: MEDIUM
  
  # B321: ftplib
  ftplib:
    severity: HIGH
  
  # B322: input
  input:
    severity: HIGH
  
  # B323: unverified_context
  unverified_context:
    severity: MEDIUM
  
  # B324: hashlib_md5
  hashlib_md5:
    severity: MEDIUM
  
  # B325: tempnam
  tempnam:
    severity: MEDIUM
  
  # B401: import_telnetlib
  import_telnetlib:
    severity: HIGH
  
  # B402: import_ftplib
  import_ftplib:
    severity: HIGH
  
  # B403: import_pickle
  import_pickle:
    severity: LOW
  
  # B404: import_subprocess
  import_subprocess:
    severity: LOW
  
  # B405: import_xml_etree
  import_xml_etree:
    severity: LOW
  
  # B406: import_xml_sax
  import_xml_sax:
    severity: LOW
  
  # B407: import_xml_expat
  import_xml_expat:
    severity: LOW
  
  # B408: import_xml_minidom
  import_xml_minidom:
    severity: LOW
  
  # B409: import_xml_pulldom
  import_xml_pulldom:
    severity: LOW
  
  # B410: import_lxml
  import_lxml:
    severity: LOW
  
  # B411: import_xmlrpclib
  import_xmlrpclib:
    severity: HIGH
  
  # B412: import_httpoxy
  import_httpoxy:
    severity: HIGH
  
  # B413: import_pycrypto
  import_pycrypto:
    severity: HIGH
  
  # B501: request_with_no_cert_validation
  request_with_no_cert_validation:
    severity: HIGH
  
  # B502: ssl_with_bad_version
  ssl_with_bad_version:
    severity: HIGH
  
  # B503: ssl_with_bad_defaults
  ssl_with_bad_defaults:
    severity: MEDIUM
  
  # B504: ssl_with_no_version
  ssl_with_no_version:
    severity: HIGH
  
  # B505: weak_cryptographic_key
  weak_cryptographic_key:
    severity: HIGH
  
  # B506: yaml_load
  yaml_load:
    severity: MEDIUM
  
  # B507: ssh_no_host_key_verification
  ssh_no_host_key_verification:
    severity: HIGH
  
  # B601: paramiko_calls
  paramiko_calls:
    severity: MEDIUM
  
  # B602: subprocess_popen_with_shell_equals_true
  subprocess_popen_with_shell_equals_true:
    severity: HIGH
  
  # B603: subprocess_without_shell_equals_true
  subprocess_without_shell_equals_true:
    severity: LOW
  
  # B604: any_other_function_with_shell_equals_true
  any_other_function_with_shell_equals_true:
    severity: HIGH
  
  # B605: start_process_with_a_shell
  start_process_with_a_shell:
    severity: HIGH
  
  # B606: start_process_with_no_shell
  start_process_with_no_shell:
    severity: LOW
  
  # B607: start_process_with_partial_path
  start_process_with_partial_path:
    severity: LOW
  
  # B608: hardcoded_sql_expressions
  hardcoded_sql_expressions:
    severity: MEDIUM
  
  # B609: linux_commands_wildcard_injection
  linux_commands_wildcard_injection:
    severity: HIGH
  
  # B610: django_extra_used
  django_extra_used:
    severity: MEDIUM
  
  # B611: django_rawsql_used
  django_rawsql_used:
    severity: MEDIUM
  
  # B701: jinja2_autoescape_false
  jinja2_autoescape_false:
    severity: HIGH
  
  # B702: use_of_mako_templates
  use_of_mako_templates:
    severity: MEDIUM
  
  # B703: django_mark_safe
  django_mark_safe:
    severity: MEDIUM
